### Probar login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "laura.gomez@vitaltrack.com",
  "password": "EncryptedPassword123!"
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   